# SPDX-License-Identifier: Apache-2.0
#
# libgrok_policyd: TCB C ABI only (no nng/uv/systemd/cap/c-capnproto).
# grok-policyd CLI + wire tests: nng + c-capnproto (pkg-config) + host stack.

VERSION       := $(shell tr -d '[:space:]' < VERSION)
VERSION_MAJOR := $(word 1,$(subst ., ,$(VERSION)))
VERSION_MINOR := $(word 2,$(subst ., ,$(VERSION)))
VERSION_PATCH := $(word 3,$(subst ., ,$(VERSION)))
API_VERSION   := $(shell tr -d '[:space:]' < API_VERSION)

CC       ?= cc
CFLAGS   ?= -std=c11 -Wall -Wextra -Werror -O2 -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200809L
CPPFLAGS += -Iinclude -Isrc -Itests \
	-Ithird_party/cwalk \
	-Ithird_party/bsdcompat/include
LDFLAGS  ?=
PREFIX   ?= /usr/local
PICFLAGS := -fPIC

CMOCKA_CFLAGS := $(shell pkg-config --cflags cmocka 2>/dev/null)
CMOCKA_LIBS   := $(shell pkg-config --libs cmocka 2>/dev/null)
NNG_CFLAGS := $(shell pkg-config --cflags nng 2>/dev/null)
NNG_LIBS   := $(shell pkg-config --libs nng 2>/dev/null)
ifeq ($(NNG_LIBS),)
NNG_LIBS := -lnng
endif
SYSTEMD_CFLAGS := $(shell pkg-config --cflags libsystemd 2>/dev/null)
SYSTEMD_LIBS   := $(shell pkg-config --libs libsystemd 2>/dev/null)
ifeq ($(SYSTEMD_LIBS),)
SYSTEMD_LIBS := -lsystemd
endif
CAP_CFLAGS := $(shell pkg-config --cflags libcap 2>/dev/null)
CAP_LIBS   := $(shell pkg-config --libs libcap 2>/dev/null)
ifeq ($(CAP_LIBS),)
CAP_LIBS := -lcap
endif

# HaoZeke/c-capnproto from rg-forge (or any pkg-config provider). Required for wire/CLI.
CAPNP_C_CFLAGS := $(shell pkg-config --cflags c-capnproto 2>/dev/null)
CAPNP_C_LIBS   := $(shell pkg-config --libs c-capnproto 2>/dev/null)
ifeq ($(CAPNP_C_LIBS),)
$(error c-capnproto not found (pkg-config c-capnproto). Install from https://repo.prefix.dev/rg-forge or pixi.)
endif

# Wire/CLI only — never DT_NEEDED of the shared TCB lib.
WIRE_CPPFLAGS := $(CPPFLAGS) -Ischema $(CAPNP_C_CFLAGS)
HOST_LIBS := $(NNG_LIBS) $(SYSTEMD_LIBS) $(CAP_LIBS) $(CAPNP_C_LIBS)
HOST_CFLAGS := $(NNG_CFLAGS) $(SYSTEMD_CFLAGS) $(CAP_CFLAGS) $(CAPNP_C_CFLAGS)

BUILD := build

LIB_SRCS := src/paths.c src/unix_dir.c src/action_log.c \
	src/cgroup.c src/policy.c src/supervisor.c src/version.c
LIB_OBJS := $(addprefix $(BUILD)/,$(notdir $(LIB_SRCS:.c=.o)))
LIB_PIC_OBJS := $(addprefix $(BUILD)/pic-,$(notdir $(LIB_SRCS:.c=.o)))
LIB_VENDOR_OBJS := $(BUILD)/vendor-cwalk.o \
	$(BUILD)/vendor-strlcpy.o $(BUILD)/vendor-strlcat.o

WIRE_OBJS := $(BUILD)/wire-codec_c_capn.o $(BUILD)/wire-serve.o \
	$(BUILD)/wire-policy.capnp.o
HOST_OBJS := $(BUILD)/host_platform.o

TEST_SRCS := tests/harness.c \
	tests/test_paths.c \
	tests/test_lifecycle.c \
	tests/test_kill_tree.c \
	tests/test_action_log.c \
	tests/test_persist.c \
	tests/test_policy.c \
	tests/test_version.c \
	tests/test_wire_serve.c \
	tests/test_main.c
TEST_OBJS := $(addprefix $(BUILD)/,$(notdir $(TEST_SRCS:.c=.o)))

SONAME     := libgrok_policyd.so.$(VERSION_MAJOR)
REAL_SO    := libgrok_policyd.so.$(VERSION)
STATIC_LIB := $(BUILD)/libgrok_policyd.a
SHARED_LIB := $(BUILD)/$(REAL_SO)

.PHONY: all clean test lib install uninstall example doxygen docs pc check-version test-wire schema

all: lib $(BUILD)/grok-policyd test

lib: check-version $(STATIC_LIB) $(SHARED_LIB) $(BUILD)/libgrok_policyd.so $(BUILD)/$(SONAME) pc

$(BUILD):
	mkdir -p $(BUILD)

$(BUILD)/%.o: src/%.c | $(BUILD)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

$(BUILD)/pic-%.o: src/%.c | $(BUILD)
	$(CC) $(CPPFLAGS) $(CFLAGS) $(PICFLAGS) -c -o $@ $<

$(BUILD)/host_platform.o: src/host_platform.c | $(BUILD)
	$(CC) $(WIRE_CPPFLAGS) $(CFLAGS) $(HOST_CFLAGS) -c -o $@ $<

$(BUILD)/vendor-cwalk.o: third_party/cwalk/cwalk.c | $(BUILD)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

$(BUILD)/vendor-strlcpy.o: third_party/bsdcompat/strlcpy.c | $(BUILD)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

$(BUILD)/vendor-strlcat.o: third_party/bsdcompat/strlcat.c | $(BUILD)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c -o $@ $<

$(BUILD)/wire-%.o: src/wire/%.c schema/policy.capnp.h | $(BUILD)
	$(CC) $(WIRE_CPPFLAGS) $(CFLAGS) $(HOST_CFLAGS) -c -o $@ $<

$(BUILD)/wire-policy.capnp.o: schema/policy.capnp.c schema/policy.capnp.h | $(BUILD)
	$(CC) $(WIRE_CPPFLAGS) $(CFLAGS) -Wno-unused-parameter -c -o $@ $<

$(BUILD)/%.o: tests/%.c schema/policy.capnp.h | $(BUILD)
	$(CC) $(WIRE_CPPFLAGS) $(CFLAGS) $(CMOCKA_CFLAGS) $(HOST_CFLAGS) \
		-Wno-format-truncation -c -o $@ $<

# Generated by capnpc-c; never committed (see .gitignore).
schema/policy.capnp.c schema/policy.capnp.h: schema/policy.capnp
	command -v capnp >/dev/null || { echo "capnp not found"; exit 1; }
	command -v capnpc-c >/dev/null || { echo "capnpc-c not found (install c-capnproto)"; exit 1; }
	cd schema && capnp compile -o $$(command -v capnpc-c) policy.capnp

$(STATIC_LIB): $(LIB_OBJS) $(LIB_VENDOR_OBJS)
	$(AR) rcs $@ $^

$(SHARED_LIB): $(LIB_PIC_OBJS) $(LIB_VENDOR_OBJS)
	$(CC) -shared -Wl,-soname,$(SONAME) -o $@ $^ $(LDFLAGS)

$(BUILD)/libgrok_policyd.so: $(SHARED_LIB)
	ln -sfn $(REAL_SO) $@

$(BUILD)/$(SONAME): $(SHARED_LIB)
	ln -sfn $(REAL_SO) $@

$(BUILD)/grok-policyd: $(BUILD)/grok-policyd.o $(WIRE_OBJS) $(HOST_OBJS) $(STATIC_LIB)
	$(CC) $(CFLAGS) -o $@ $(BUILD)/grok-policyd.o $(WIRE_OBJS) $(HOST_OBJS) $(STATIC_LIB) $(LDFLAGS) $(HOST_LIBS)

$(BUILD)/supervisor_test: $(TEST_OBJS) $(WIRE_OBJS) $(HOST_OBJS) $(STATIC_LIB)
	test -n "$(CMOCKA_LIBS)" || (echo "error: cmocka not found" && exit 1)
	$(CC) $(CFLAGS) -o $@ $(TEST_OBJS) $(WIRE_OBJS) $(HOST_OBJS) $(STATIC_LIB) $(LDFLAGS) $(CMOCKA_LIBS) $(HOST_LIBS)

$(BUILD)/example_minimal: examples/c/minimal.c $(STATIC_LIB) | $(BUILD)
	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ examples/c/minimal.c $(STATIC_LIB) $(LDFLAGS)

example: $(BUILD)/example_minimal

test-wire: $(BUILD)/test_wire_frame
	$(BUILD)/test_wire_frame

$(BUILD)/test_wire_frame: tests/test_wire_frame.c $(WIRE_OBJS) $(HOST_OBJS) $(STATIC_LIB) | $(BUILD)
	$(CC) $(WIRE_CPPFLAGS) $(CFLAGS) $(HOST_CFLAGS) -o $@ tests/test_wire_frame.c $(WIRE_OBJS) $(HOST_OBJS) $(STATIC_LIB) $(LDFLAGS) $(HOST_LIBS)

test: lib $(BUILD)/grok-policyd $(BUILD)/supervisor_test test-wire
	test -n "$(CMOCKA_LIBS)" || (echo "error: cmocka not found" && exit 1)
	$(BUILD)/supervisor_test
	bash scripts/check_shared_libs.sh
	bash scripts/smoke_serve_signal.sh

pc: $(BUILD)/grok-policyd.pc

check-version:
	bash scripts/check-version.sh

$(BUILD)/grok-policyd.pc: packaging/grok-policyd.pc.in | $(BUILD)
	sed -e 's|@PREFIX@|$(PREFIX)|g' -e 's|@VERSION@|$(VERSION)|g' $< > $@

# Official capnp + HaoZeke capnpc-c (from c-capnproto package).
# Writes schema/policy.capnp.{c,h} (gitignored build products).
schema: schema/policy.capnp.c schema/policy.capnp.h

install: lib $(BUILD)/grok-policyd
	install -d $(DESTDIR)$(PREFIX)/include/grok-policyd
	install -d $(DESTDIR)$(PREFIX)/lib
	install -d $(DESTDIR)$(PREFIX)/lib/pkgconfig
	install -d $(DESTDIR)$(PREFIX)/bin
	install -m 644 include/grok-policyd/supervisor.h $(DESTDIR)$(PREFIX)/include/grok-policyd/
	install -m 644 $(STATIC_LIB) $(DESTDIR)$(PREFIX)/lib/
	install -m 755 $(SHARED_LIB) $(DESTDIR)$(PREFIX)/lib/
	ln -sfn $(REAL_SO) $(DESTDIR)$(PREFIX)/lib/libgrok_policyd.so
	ln -sfn $(REAL_SO) $(DESTDIR)$(PREFIX)/lib/$(SONAME)
	install -m 644 $(BUILD)/grok-policyd.pc $(DESTDIR)$(PREFIX)/lib/pkgconfig/grok-policyd.pc
	install -m 755 $(BUILD)/grok-policyd $(DESTDIR)$(PREFIX)/bin/grok-policyd

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/include/grok-policyd/supervisor.h
	rmdir $(DESTDIR)$(PREFIX)/include/grok-policyd 2>/dev/null || true
	rm -f $(DESTDIR)$(PREFIX)/lib/libgrok_policyd.a
	rm -f $(DESTDIR)$(PREFIX)/lib/libgrok_policyd.so
	rm -f $(DESTDIR)$(PREFIX)/lib/$(SONAME)
	rm -f $(DESTDIR)$(PREFIX)/lib/$(REAL_SO)
	rm -f $(DESTDIR)$(PREFIX)/lib/pkgconfig/grok-policyd.pc
	rm -f $(DESTDIR)$(PREFIX)/bin/grok-policyd

doxygen:
	command -v doxygen >/dev/null || { echo "doxygen not found"; exit 1; }
	mkdir -p docs/build/doxygen
	cd docs && doxygen Doxyfile

docs: doxygen
	command -v sphinx-build >/dev/null || { echo "sphinx-build not found"; exit 1; }
	sphinx-build -W -b html docs/source docs/build/html

clean:
	rm -rf $(BUILD) docs/build
