# Cap'n layout for Policy.ShellView / PathProbe (schema ordinal packing).
# Regenerated by hand when policy.capnp field order changes; full capnpc-janet
# will emit this module. Indices match the Cap'n Proto encoding rules:
#   data fields by size/ordinal, pointer fields by ordinal among pointers.

(def ShellView
  @{:dwords 1
    :pwords 3
    :under-workspace-bit 0
    :cwd-ptr 0
    :argv-ptr 1
    :path-probes-ptr 2})

(def PathProbe
  @{:dwords 1
    :pwords 3
    :exists-bit 0
    :arg-ptr 0
    :resolved-ptr 1
    :head-ptr 2})
