#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate PolicyReason encyclopedia maps from schema/policy.capnp.

Parses the Cap'n enum PolicyReason (authoritative ordinals + names + nearby
comments) and writes:

  playground/astro/src/lib/policy-reasons.generated.json
  playground/astro/src/lib/policy-reasons.generated.ts
  playground/astro/src/data/encyclopedia/generated/<code>-<name>.md  (stubs)

Hand-authored product notes live in
playground/astro/src/lib/encyclopedia-notes.ts and are not overwritten.

Usage:
  python3 playground/scripts/gen-encyclopedia.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "schema" / "policy.capnp"
ASTRO_LIB = ROOT / "playground" / "astro" / "src" / "lib"
STUB_DIR = (
    ROOT / "playground" / "astro" / "src" / "data" / "encyclopedia" / "generated"
)

ENUM_OPEN = re.compile(r"^enum\s+PolicyReason\s*\{")
FIELD = re.compile(r"^(\w+)\s+@(\d+)\s*;\s*(?:#\s*(.*))?$")
COMMENT = re.compile(r"^#\s?(.*)$")


def parse_policy_reason(text: str) -> list[dict]:
    """Parse PolicyReason enum into [{code, name, comment, group}, ...].

    Comment rules (matches schema style in policy.capnp):
    - After a blank line, comment lines update the current *group* for
      subsequent fields.
    - Comment lines immediately after a field (no blank) attach as that
      field's *comment* (trailing doc).
    - Inline ``name @N; # doc`` also sets comment.
    """
    lines = text.splitlines()
    in_enum = False
    depth = 0
    group = ""
    after_blank = True
    pending_group: list[str] = []
    pending_field_doc: list[str] = []
    entries: list[dict] = []

    def flush_field_doc() -> None:
        nonlocal pending_field_doc
        if pending_field_doc and entries:
            doc = " ".join(p for p in pending_field_doc if p).strip()
            if doc:
                prev = entries[-1]
                if prev["comment"]:
                    prev["comment"] = f"{prev['comment']} {doc}".strip()
                else:
                    prev["comment"] = doc
        pending_field_doc = []

    for raw in lines:
        line = raw.strip()
        if not in_enum:
            if ENUM_OPEN.match(line):
                in_enum = True
                depth = line.count("{") - line.count("}")
            continue

        depth += line.count("{") - line.count("}")
        if depth <= 0:
            flush_field_doc()
            break

        if not line:
            flush_field_doc()
            after_blank = True
            continue

        m_field = FIELD.match(line)
        if m_field:
            if pending_group:
                group = " ".join(pending_group).strip()
                pending_group = []
            flush_field_doc()
            name, code_s, inline = (
                m_field.group(1),
                m_field.group(2),
                m_field.group(3),
            )
            entries.append(
                {
                    "code": int(code_s),
                    "name": name,
                    "comment": (inline or "").strip(),
                    "group": group,
                }
            )
            after_blank = False
            continue

        m_c = COMMENT.match(line)
        if m_c:
            body = m_c.group(1).strip()
            if not body:
                continue
            if after_blank or not entries:
                # Section / group header for following fields
                pending_group.append(body)
            else:
                # Trailing doc for previous field
                pending_field_doc.append(body)
            continue

    flush_field_doc()
    entries.sort(key=lambda e: e["code"])
    return entries


def write_json(entries: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "source": "schema/policy.capnp",
        "enum": "PolicyReason",
        "generatedBy": "playground/scripts/gen-encyclopedia.py",
        "reasons": entries,
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_ts(entries: list[dict], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Auto-generated by playground/scripts/gen-encyclopedia.py — do not edit. */",
        "/* Source: schema/policy.capnp enum PolicyReason */",
        "",
        "export interface PolicyReasonEntry {",
        "  code: number;",
        "  name: string;",
        "  comment: string;",
        "  group: string;",
        "}",
        "",
        "export const POLICY_REASONS: PolicyReasonEntry[] = [",
    ]
    for e in entries:
        comment = e["comment"].replace("\\", "\\\\").replace('"', '\\"')
        group = e["group"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'  {{ code: {e["code"]}, name: "{e["name"]}", '
            f'comment: "{comment}", group: "{group}" }},'
        )
    lines.append("];")
    lines.append("")
    lines.append("/** Stable PolicyReason names keyed by ordinal. */")
    lines.append("export const REASON_NAMES: Record<number, string> = {")
    for e in entries:
        lines.append(f'  {e["code"]}: "{e["name"]}",')
    lines.append("};")
    lines.append("")
    lines.append("export function reasonLabel(code: number): string {")
    lines.append('  return REASON_NAMES[code] ?? `code_${code}`;')
    lines.append("}")
    lines.append("")
    lines.append(
        "export function getReason(code: number): PolicyReasonEntry | undefined {"
    )
    lines.append("  return POLICY_REASONS.find((r) => r.code === code);")
    lines.append("}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_stubs(entries: list[dict], stub_dir: Path) -> None:
    if stub_dir.exists():
        for old in stub_dir.glob("*.md"):
            old.unlink()
    stub_dir.mkdir(parents=True, exist_ok=True)
    for e in entries:
        body_comment = e["comment"] or "(no schema comment)"
        group = e["group"] or "ungrouped"
        text = (
            f"---\n"
            f'code: {e["code"]}\n'
            f'name: {e["name"]}\n'
            f'group: "{group}"\n'
            f"generated: true\n"
            f"---\n"
            f"\n"
            f"# {e['name']} ({e['code']})\n"
            f"\n"
            f"Schema: `schema/policy.capnp` enum `PolicyReason`.\n"
            f"\n"
            f"**Group:** {group}\n"
            f"\n"
            f"{body_comment}\n"
            f"\n"
            f"Stub generated by `playground/scripts/gen-encyclopedia.py`.\n"
            f"Product notes (when present) live in "
            f"`playground/astro/src/lib/encyclopedia-notes.ts`.\n"
        )
        path = stub_dir / f'{e["code"]:02d}-{e["name"]}.md'
        path.write_text(text, encoding="utf-8")


def main() -> int:
    if not SCHEMA.is_file():
        print(f"error: missing schema {SCHEMA}", file=sys.stderr)
        return 1
    text = SCHEMA.read_text(encoding="utf-8")
    entries = parse_policy_reason(text)
    if not entries:
        print("error: no PolicyReason entries parsed", file=sys.stderr)
        return 1
    codes = [e["code"] for e in entries]
    expected = list(range(min(codes), max(codes) + 1))
    if codes != expected:
        print(
            f"warn: non-contiguous ordinals {codes[0]}..{codes[-1]} "
            f"(got {len(codes)} entries, expected {len(expected)})",
            file=sys.stderr,
        )
    if min(codes) != 0:
        print(f"warn: first ordinal is {min(codes)}, expected 0", file=sys.stderr)

    json_path = ASTRO_LIB / "policy-reasons.generated.json"
    ts_path = ASTRO_LIB / "policy-reasons.generated.ts"
    write_json(entries, json_path)
    write_ts(entries, ts_path)
    write_stubs(entries, STUB_DIR)

    def rel(p: Path) -> Path:
        return p.relative_to(ROOT)

    print(f"OK: {len(entries)} PolicyReason entries (0..{max(codes)})")
    print(f"  {rel(json_path)}")
    print(f"  {rel(ts_path)}")
    print(f"  {rel(STUB_DIR)}/ ({len(entries)} stubs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
