//! Compile phronesis and everything it stands on from `vendor/`: the Janet
//! amalgamation, c-capnproto, capnp-janet, the generated Cap'n Proto C for
//! the schema, the library's own sources and the shell-check wrapper. One
//! static library. The schema's C is generated by capnpc-c when the schema
//! changes (vendor.sh) and checked in, so a build needs only a C compiler;
//! every check still travels as a Cap'n Proto ShellCheck and PolicyDecision.

use std::path::{Path, PathBuf};

fn sources(dir: &Path, skip: &[&str]) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "c"))
        .filter(|p| {
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
            !skip.contains(&name)
        })
        .collect();
    out.sort();
    out
}

fn main() {
    let vendor = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("vendor");
    println!("cargo:rerun-if-changed=vendor");
    println!("cargo:rerun-if-changed=build.rs");
    if !vendor.join("PINS").is_file() {
        panic!(
            "{} is empty: run crates/phronesis-sys/vendor.sh [MESON_BUILD_DIR]",
            vendor.display()
        );
    }

    // Janet, warnings off as the meson build has them: upstream code.
    let mut janet = cc::Build::new();
    janet
        .file(vendor.join("janet/janet.c"))
        .include(vendor.join("janet"))
        .define("JANET_API", "")
        .define("JANET_NO_PROCESSES", None)
        .define("JANET_SPAWN_NO_CHDIR", None)
        .warnings(false)
        .flag_if_supported("-Wno-implicit-function-declaration")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-sign-compare")
        .flag_if_supported("-std=gnu11")
        .pic(true);
    janet.compile("janet_amalg");

    let mut capn = cc::Build::new();
    capn.files(sources(&vendor.join("c-capnproto/lib"), &[]))
        .files(sources(&vendor.join("c-capnproto/compiler"), &[]))
        .include(vendor.join("c-capnproto/lib"))
        .include(vendor.join("c-capnproto/compiler"))
        .define("CAPNP_C_STATIC", None)
        .define("CAPNP_C_BUILDING", None)
        .warnings(false)
        .flag_if_supported("-std=gnu11")
        .pic(true);
    capn.compile("capnp_c");

    let mut cj = cc::Build::new();
    cj.files(sources(&vendor.join("capnp-janet/src"), &["janet_mod.c"]))
        .include(vendor.join("capnp-janet/include"))
        .include(vendor.join("janet"))
        .define("CAPNP_JANET_STATIC", None)
        .define("CAPNP_JANET_BUILDING", None)
        .define("JANET_API", "")
        .warnings(false)
        .flag_if_supported("-std=gnu11")
        .pic(true);
    cj.compile("capnp_janet");

    // The library itself, its Janet module for Cap'n, the generated schema
    // C and the shell-check wrapper that builds a ShellCheck message.
    let mut lib = cc::Build::new();
    lib.files(sources(&vendor.join("phronesis/src"), &["phronesis.c"]))
        .file(vendor.join("capnp-janet/src/janet_mod.c"))
        .files(sources(&vendor.join("gen"), &[]))
        .file("src/native/shell_check.c")
        .include(vendor.join("phronesis/include"))
        .include(vendor.join("phronesis/src"))
        .include(vendor.join("gen"))
        .include(vendor.join("janet"))
        .include(vendor.join("c-capnproto/lib"))
        .include(vendor.join("c-capnproto/compiler"))
        .include(vendor.join("capnp-janet/include"))
        .define("_GNU_SOURCE", None)
        .define("JANET_API", "")
        .define("CAPNP_C_STATIC", None)
        .define("CAPNP_JANET_STATIC", None)
        // No install prefix exists: the pack is written out at run time and
        // reached through PHRONESIS_PREFIX.
        .define("PHRONESIS_DEFAULT_JANET_PACK", "\"/nonexistent/phronesis/policy/shell.janet\"")
        .warnings(false)
        .flag_if_supported("-std=gnu11")
        .pic(true);
    lib.compile("phronesis");

    println!("cargo:rustc-link-lib=m");
    println!("cargo:rustc-link-lib=dl");
    println!("cargo:rustc-link-lib=pthread");
    println!("cargo:rerun-if-changed=src/native/shell_check.c");
}
