/**
 * Fixture catalog types + helpers. Catalog JSON is generated by
 * playground/scripts/copy-wasm-assets.mjs at prebuild/predev.
 */

import catalogJson from "./fixture-catalog.json";

export type DecisionOrdinal = 0 | 1 | 2;

export interface FixtureExpect {
  decision: number;
  code: number;
}

export interface FixtureCatalogEntry {
  id: string;
  domain: string;
  method: string;
  description: string;
  file: string;
  expect: FixtureExpect | null;
}

export interface FixtureBody {
  id: string;
  description?: string;
  method: string;
  agentId?: { hi: number; lo: number };
  cwd?: string;
  argv?: string[];
  path?: string;
  action?: string | number;
  memfs?: Record<string, string>;
  expect?: FixtureExpect;
  bin?: string;
}

export const FIXTURE_CATALOG: FixtureCatalogEntry[] =
  catalogJson as FixtureCatalogEntry[];

export function listFixtures(): FixtureCatalogEntry[] {
  return FIXTURE_CATALOG;
}

export function getFixtureMeta(id: string): FixtureCatalogEntry | undefined {
  return FIXTURE_CATALOG.find((f) => f.id === id);
}

/** Resolve public URL for a fixture JSON under the site base. */
export function fixturePublicUrl(file: string, base = import.meta.env.BASE_URL): string {
  const b = base.endsWith("/") ? base : base + "/";
  return `${b}fixtures/${file}`;
}

export async function fetchFixture(
  id: string,
  base = import.meta.env.BASE_URL,
): Promise<FixtureBody> {
  const meta = getFixtureMeta(id);
  if (!meta) throw new Error(`unknown fixture: ${id}`);
  const url = fixturePublicUrl(meta.file, base);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`fetch fixture ${id}: HTTP ${res.status}`);
  return (await res.json()) as FixtureBody;
}

export const DECISION_LABEL: Record<number, string> = {
  0: "DENY",
  1: "ALLOW",
  2: "PROMPT",
};

/** Generated from schema/policy.capnp (playground/scripts/gen-encyclopedia.py). */
export {
  REASON_NAMES,
  POLICY_REASONS,
  reasonLabel,
  getReason,
  type PolicyReasonEntry,
} from "./policy-reasons.generated";
